# Site settings
title: Open Government Data Initiative
author: Travis Corcoran
email: travis4nh@tjic.com
description: "An initiative to get government to proactively, not reactively, publish internal data so that citizens and non-profits can build a variety of dashboards allowing the people to understand what the government is doing."
site.github: https://github.com/travis4nh/open-gov-data-init
site.github.is_project_page: true
site.github.repository_url: https://github.com/travis4nh/open-gov-data-init

# Theme
theme: jekyll-theme-cayman

baseurl: /


# Publishing source
# publishing_source: main
